version: 2.1

orbs:
  mirci: libmir/upload_docs@0.3.0

workflows:
  version: 2
  build-deploy:
    jobs:
      - mirci/test:
          filters:
            tags:
              only: /^v(\d)+(\.(\d)+)+$/
